apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: catalog
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - catalog.keptnorders-production.35.204.59.55.xip.io
  - catalog
  http:
  - route:
    - destination:
        host: catalog-canary.keptnorders-production.svc.cluster.local
    - destination:
        host: catalog-primary.keptnorders-production.svc.cluster.local
      weight: 100
